### ISSUE TITLE
Persistent Volume / PVC for GlusterFS-GCE 

### ISSUE THREAD

**Issue by rasekar2000** [rimusz/glusterfs-gce#6]
Best Practice to access glusterFs on GCE?

Option 1) 
 **GlusterFS IPs as Endpoints**
https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/glusterfs
   This is working fine .
Option 2)
 **Creating PersistentVolume and Access it via PersistentVolumeClaim.**
 https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/vsphere
   I haven't tried this. But seems an option. But not sure, will it work? If you think this will not work or not applicable, we can create an enhancement request. 

@rimusz / @janakiramm : Please share your thoughts!

Thanks and Regards,
Raj

**Comment by rimusz** [comment]
@rasekar2000 I have successfully used option 1 with PV/PVC:
test1_pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-cluster1"
    path: "test1"
```

test1_pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test1-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```
